// <auto-generated />
namespace DragonsBlood.AppMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AfterMassImport : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AfterMassImport));
        
        string IMigrationMetadata.Id
        {
            get { return "201604111746464_AfterMassImport"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
