// <auto-generated />
namespace DragonsBlood.AppMigrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddedLinkBetweenRoomsAndUsers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddedLinkBetweenRoomsAndUsers));
        
        string IMigrationMetadata.Id
        {
            get { return "201605031925482_AddedLinkBetweenRoomsAndUsers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
